version: '3.7'

services:
  icecast2:
    image: kugichka/nesorter-icecast:latest
    container_name: icecast2_0
    restart: always
    environment:
      - SHOUT_ADMIN_EMAIL=your@address.com

      - SHOUT_SOURCE_PASSWORD=spass
      - SHOUT_RELAY_PASSWORD=rpass
      - SHOUT_ADMIN_USERNAME=admin
      - SHOUT_ADMIN_PASSWORD=apass

      - SHOUT_SYSTEM_TUNE_LOGLEVEL=3
      - SHOUT_SYSTEM_TUNE_HOSTNAME=localhost
      - SHOUT_SYSTEM_TUNE_CLIENTS=100
      - SHOUT_SYSTEM_TUNE_SOURCES=2
      - SHOUT_SYSTEM_TUNE_THREADPOOL=5
      - SHOUT_SYSTEM_TUNE_QUEUE_SIZE=524288
      - SHOUT_SYSTEM_TUNE_CLIENT_TIMEOUT=30
      - SHOUT_SYSTEM_TUNE_HEADER_TIMEOUT=15
      - SHOUT_SYSTEM_TUNE_SOURCE_TIMEOUT=10
      - SHOUT_SYSTEM_TUNE_BURST_ON_CONNECT=1
      - SHOUT_SYSTEM_TUNE_BURST_SIZE=65535

      - SHOUT_MOUNT=stream.mp3
      - SHOUT_USER=stream
      - SHOUT_PASSWORD=12345678
      - SHOUT_STREAM_NAME=NameOfYourStream
      - SHOUT_STREAM_DESCRIPTION=YourStreamDescription
    ports:
      - "8000:8000"

  api:
    user: node
    image: kugichka/nesorter:latest
    container_name: nesorter_0
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse:ro
      - /Users/Username/Music:/home/node/lib:rw
      - ./data/prisma:/home/node/prisma/db:rw
      - ./data/covers:/home/node/dist/API/routes/assets/covers:rw
    environment:
      - SHOUT_HOST=icecast2
      - SHOUT_MOUNT=stream.mp3
      - SHOUT_USER=stream
      - SHOUT_PASSWORD=12345678
      - SHOUT_URL=http://localhost:8000/stream.mp3
      - SHOUT_DESCRIPTION=Its test stream
      - SHOUT_ADMIN_USER=admin
      - SHOUT_ADMIN_PASSWORD=apass
      - ADMIN_TOKEN=secret

      - CONTENT_ROOT_DIR_PATH=/home/node/lib
      - TZ_HOURS_SHIFT=4

      - PLAYING_MODE=hardware
      - HARDWARE_PLAYER_FFMPEG_DRIVER=pulse
      - HARDWARE_PLAYER_FFMPEG_DEVICE=alsa_output.pci-0000_0d_00.4.analog-stereo.monitor

      - MPV_FADE_TIME=5
      - FFMPEG_BITRATE=320
      - FFMPEG_FORMAT=mp3

      - PULSE_SERVER=unix:/run/user/1000/pulse/native
